FROM golang:1.12-alpine

RUN apk update; \
    apk add --no-cache git; \
    mkdir go-auth-manager;

WORKDIR go-auth-manager

COPY go.mod .
COPY go.sum .

RUN go mod download

CMD CGO_ENABLED=0 go test ./... -v