// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

import (
	"github.com/LucasFrezarini/go-auth-manager/jsonwebtoken"
	"github.com/LucasFrezarini/go-auth-manager/models"
)

type AuthUserPayload struct {
	User  *models.User `json:"user"`
	Token string       `json:"token"`
}

type CreateUserInput struct {
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Roles    []string `json:"roles"`
}

type LoginUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ValidateTokenPayload struct {
	Claims *jsonwebtoken.Claims `json:"claims"`
	User   *models.User         `json:"user"`
	Valid  bool                 `json:"valid"`
}
